name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Verify JAR file
      run: ls -l build/libs/

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: build/libs/*.jar

  use-artifact:
    runs-on: windows-latest
    needs: build-java

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: jar-artifact
        path: D:/DevOps2024/Sample learning

    - name: List downloaded files
      run: dir "D:\DevOps2024\Sample learning"
